config/routes.rb
Rails.application.routes.draw do
  root 'displaymovies#index'

  resources :movie_records

end

app/models/movie.rb
class Movie
  include Mongoid::Document
  field :id, type: Int
  field :name, type: String
  field :media_type, type: String
  field :first_air_date, type: String
  field :popularity, type: Float
  field :vote_count, type: Int
end

app/models/movie_record.rb
class MovieRecord
  include Mongoid::Document
  field :movie_id, type: String
  field :name, type: String
  field :media_type, type: String
  field :first_air_date, type: String
  field :popularity, type: String
  field :vote_count, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/displaymovies_controller.rb
class DisplaymoviesController < ApplicationController
  def index
  end
end

app/controllers/movie_records_controller.rb
require 'json'
class MovieRecordsController < ApplicationController
  before_action :set_movie_record, only: [:show, :edit, :update, :destroy]

  # GET /movie_records
  # GET /movie_records.json
  def index
    @movie_records = MovieRecord.all
  end

  # GET /movie_records/1
  # GET /movie_records/1.json
  def show
    render json: MovieRecord.find(params[:id])
  end

  # GET /movie_records/new
  def new
    @movie_record = MovieRecord.new
  end

  # GET /movie_records/1/edit
  def edit
  end

  # POST /movie_records
  # POST /movie_records.json
  def create
    @movie_record = MovieRecord.new(movie_record_params)

    respond_to do |format|
      if @movie_record.save
        format.html { redirect_to @movie_record, notice: 'Movie record was successfully created.' }
        format.json { render :show, status: :created, location: @movie_record }
      else
        format.html { render :new }
        format.json { render json: @movie_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_records/1
  # PATCH/PUT /movie_records/1.json
  def update
    respond_to do |format|
      if @movie_record.update(movie_record_params)
        format.html { redirect_to @movie_record, notice: 'Movie record was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie_record }
      else
        format.html { render :edit }
        format.json { render json: @movie_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_records/1
  # DELETE /movie_records/1.json
  def destroy
    @movie_record.destroy
    respond_to do |format|
      format.html { redirect_to movie_records_url, notice: 'Movie record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_record
      @movie_record = MovieRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_record_params
      params.require(:movie_record).permit(:movie_id, :name, :media_type, :first_air_date, :popularity, :vote_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/displaymovies_helper.rb
module DisplaymoviesHelper
end

app/helpers/movie_records_helper.rb
module MovieRecordsHelper
end

app/views/displaymovies/index.html.erb
<h1>Movie Records</h1>
<script>
$( document ).ready(function() {
    console.log( "ready!" );
    sessionStorage.count = 0 ;
    var myVar=setInterval(function () {myTimer()}, 2000);
    function myTimer() {
          if (sessionStorage.count == 200){
              sessionStorage.count = 0;
          }
          var url = "/movie_records/";
          sessionStorage.count = parseInt(sessionStorage.count)+1 ;
          getUrl = url+sessionStorage.count;
          $.get( getUrl, function( data ) {
               // console.log(data);
                addRecordToTable(data);
               }
         );

    }
    function addRecordToTable(data){
           //console.log("inside the add record to Table\n")
           //console.log(data);
           var rowCount = $('#movie_table tr').length;
           //console.log(rowCount+"\n");
            classStr = "<tr class='info'>";

            rowString = classStr+"<td>"+data["_id"]+"</td><td>"+data["name"]+"</td><td>"+data["media_type"]+"</td><td>"+data["first_air_date"]+"</td><td>"+data["popularity"]+"</td><td>"+data["vote_count"]+"</td></tr>"
           //$('#movie_table > tbody:last').append(rowString);
           if (rowCount%20 == 0 ){
                 $('#movie_table tr:first').fadeOut(500, function() {
                 $('#movie_table tr:first').remove();
                 newRow = $(rowString).hide();
                 $('#movie_table').append(newRow);
                 newRow.fadeIn(2000);
                 });
              }
           else{
            $('#movie_table > tbody:last').append(rowString);
           }
    }

});
</script>
<div class="container">
  <h2>Movie list </h2>
  <p> Movie Details </p>
   <table class="table" id="dummy_table">
    <thead>
        <th>Movie ID</th>
        <th>Movie Name</th>
        <th>Media Type</th>
        <th>Air Date</th>
        <th>Popularity</th>
        <th>Vote Count </th>
    </thead>
    <tbody>
    </tbody>
  </table>
            
  <table class="table" id="movie_table">
    <thead>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectPhase3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="assets/bootstrap.min.css">
  <script src="assets/jquery.min.js"></script>
  <script src="assets/bootstrap.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movie_records/_form.html.erb
<%= form_for(@movie_record) do |f| %>
  <% if @movie_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_record.errors.count, "error") %> prohibited this movie_record from being saved:</h2>

      <ul>
      <% @movie_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.text_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :media_type %><br>
    <%= f.text_field :media_type %>
  </div>
  <div class="field">
    <%= f.label :first_air_date %><br>
    <%= f.text_field :first_air_date %>
  </div>
  <div class="field">
    <%= f.label :popularity %><br>
    <%= f.text_field :popularity %>
  </div>
  <div class="field">
    <%= f.label :vote_count %><br>
    <%= f.text_field :vote_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_records/edit.html.erb
<h1>Editing Movie Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_record %> |
<%= link_to 'Back', movie_records_path %>

app/views/movie_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movie Records</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Name</th>
      <th>Media type</th>
      <th>First air date</th>
      <th>Popularity</th>
      <th>Vote count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_records.each do |movie_record| %>
      <tr>
        <td><%= movie_record.movie_id %></td>
        <td><%= movie_record.name %></td>
        <td><%= movie_record.media_type %></td>
        <td><%= movie_record.first_air_date %></td>
        <td><%= movie_record.popularity %></td>
        <td><%= movie_record.vote_count %></td>
        <td><%= link_to 'Show', movie_record %></td>
        <td><%= link_to 'Edit', edit_movie_record_path(movie_record) %></td>
        <td><%= link_to 'Destroy', movie_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie record', new_movie_record_path %>

app/views/movie_records/new.html.erb
<h1>New Movie Record</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_records_path %>

app/views/movie_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @movie_record.movie_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @movie_record.name %>
</p>

<p>
  <strong>Media type:</strong>
  <%= @movie_record.media_type %>
</p>

<p>
  <strong>First air date:</strong>
  <%= @movie_record.first_air_date %>
</p>

<p>
  <strong>Popularity:</strong>
  <%= @movie_record.popularity %>
</p>

<p>
  <strong>Vote count:</strong>
  <%= @movie_record.vote_count %>
</p>

<%= link_to 'Edit', edit_movie_record_path(@movie_record) %> |
<%= link_to 'Back', movie_records_path %>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :media_type %><br>
    <%= f.text_field :media_type %>
  </div>
  <div class="field">
    <%= f.label :first_air_date %><br>
    <%= f.text_field :first_air_date %>
  </div>
  <div class="field">
    <%= f.label :popularity %><br>
    <%= f.text_field :popularity %>
  </div>
  <div class="field">
    <%= f.label :vote_count %><br>
    <%= f.text_field :vote_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Media type</th>
      <th>First air date</th>
      <th>Popularity</th>
      <th>Vote count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.id %></td>
        <td><%= movie.name %></td>
        <td><%= movie.media_type %></td>
        <td><%= movie.first_air_date %></td>
        <td><%= movie.popularity %></td>
        <td><%= movie.vote_count %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @movie.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Media type:</strong>
  <%= @movie.media_type %>
</p>

<p>
  <strong>First air date:</strong>
  <%= @movie.first_air_date %>
</p>

<p>
  <strong>Popularity:</strong>
  <%= @movie.popularity %>
</p>

<p>
  <strong>Vote count:</strong>
  <%= @movie.vote_count %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>